rule first_step:
    input: "data/A.txt"
    output: "results/output_A.txt"
    shell: "cat {input} > {output}"

rule upper_case:
    input: "results/output_A.txt"
    output: "results/uppercase_output_A.txt"
    shell: "tr '[:lower:]' '[:upper:]' < {input} > {output}"
